#!/usr/bin/env python3
"""Rakit NoctisENIX.lua dari src/.

src/main.lua berisi baris penanda `--@@INCLUDE modules/<nama>.lua@@`. Setiap penanda
diganti isi file modul tersebut (modul berbentuk `return function(ctx) ... end`, dan
main.lua membungkusnya dengan `(function() ... end)()(ctx)`).

src/inspector.lua disalin apa adanya ke NoctisENIX_Inspector.lua.

Pakai: python3 tools/build.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
MARK = re.compile(r"^--@@INCLUDE (\S+)@@\s*$")

BANNER = "-- GENERATED by tools/build.py from src/. Do not edit this file directly.\n"


def build_main(overrides=None) -> str:
    overrides = overrides or {}
    out = []
    for lineno, line in enumerate((SRC / "main.lua").read_text().splitlines(keepends=True), 1):
        m = MARK.match(line)
        if not m:
            out.append(line)
            continue
        path = overrides.get(m.group(1), SRC / m.group(1))
        if not path.is_file():
            sys.exit(f"src/main.lua:{lineno}: include not found: {m.group(1)}")
        body = path.read_text()
        if not body.endswith("\n"):
            body += "\n"
        out.append(f"-- >>> {m.group(1)}\n{body}-- <<< {m.group(1)}\n")
    return BANNER + "".join(out)


def main() -> None:
    if "--stub" in sys.argv:
        # Build khusus tes UI: intel/actions diganti stub dari tests/stubs.
        stubs = ROOT / "tests" / "stubs"
        out = ROOT / "tests" / ".debug" / "NoctisENIX_stub.lua"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(build_main({
            "modules/intel.lua": stubs / "intel.lua",
            "modules/actions.lua": stubs / "actions.lua",
        }))
        print("built", out.relative_to(ROOT))
        return
    (ROOT / "NoctisENIX.lua").write_text(build_main())
    inspector = SRC / "inspector.lua"
    if inspector.is_file():
        (ROOT / "NoctisENIX_Inspector.lua").write_text(BANNER + inspector.read_text())
    print("built NoctisENIX.lua" + (" and NoctisENIX_Inspector.lua" if inspector.is_file() else ""))


if __name__ == "__main__":
    main()
